users/urls.py
from django.urls import path

from .views import SignUpView, DetailUserView, EditUserView

app_name = "users"
urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
    path('<str:username>/', DetailUserView.as_view(), name='detail'),
    path('<str:username>/edit/', EditUserView.as_view(), name='edit'),
]

utilities/urls.py
from django.urls import path

from .views import (
    CreateUtilitiesView,
    EditUtilitiesView,
    DeleteUtilitiesView,
    DetailUtilitiesView,
    ListUtilitiesView
)

app_name = "utilities"
urlpatterns = [
    path('', ListUtilitiesView.as_view(), name='list'),
    path('create/', CreateUtilitiesView.as_view(), name='create'),
    path('<int:pk>/', DetailUtilitiesView.as_view(), name='detail'),
    path('<int:pk>/edit/', EditUtilitiesView.as_view(), name='edit'),
    path('<int:pk>/delete/', DeleteUtilitiesView.as_view(), name='delete'),
]

utilities_stats/urls.py
from django.contrib import admin
from django.conf.urls.i18n import i18n_patterns
from django.urls import path, include
from django.views.generic import TemplateView
from django.views.defaults import (
    page_not_found,
    server_error,
    permission_denied
)

from rest_framework import routers

from api.views import UserViewSet, UtilitiesViewSet
from utilities.views import HomeView

from django.conf import settings

router = routers.DefaultRouter()
router.register(r'users', UserViewSet)
router.register(r'utilities', UtilitiesViewSet)

urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path('users/', include('django.contrib.auth.urls')),
    path('users/', include('users.urls')),
    path('utilities/', include('utilities.urls')),
    path('', HomeView.as_view(), name='home'),
    path(
        'about/',
        TemplateView.as_view(template_name='about.html'),
        name='about'
    ),
)

urlpatterns += [
    path('api/', include(router.urls)),
    path(
        'api/auth/',
        include('rest_framework.urls', namespace='rest_framework'),
    ),
]


def custom_page_not_found(request):
    return page_not_found(request, None)


def custom_permission_denied(request):
    return permission_denied(request, None)


if settings.DEBUG:
    urlpatterns += i18n_patterns(
        path("404/", custom_page_not_found),
        path("403/", custom_permission_denied),
        path("500/", server_error),
    )

utilities/models.py
from django.db import models
from django.db.models import Avg, Max, Min, Sum
from django.utils.translation import gettext_lazy as _
from django.utils.dateformat import DateFormat
from django.utils.formats import get_format

from core.validators import validate_price
from users.models import UtilitiesUser


class UtilitiesManager(models.Manager):
    use_for_related_fields = True

    def get_by_owner_year(self, owner, year):
        return self.filter(owner=owner, date__year=year).order_by('date')

    def avg_field(self, owner, year, field):
        return round(self.get_by_owner_year(owner, year).aggregate(
            Avg(field))['%s__avg' % field], 3)

    def sum_field(self, owner, year, field):
        return self.get_by_owner_year(owner, year).aggregate(
            Sum(field))['%s__sum' % field]

    def max_field(self, owner, year, field):
        return self.get_by_owner_year(owner, year).aggregate(
            Max(field))['%s__max' % field]

    def min_field(self, owner, year, field):
        return self.get_by_owner_year(owner, year).aggregate(
            Min(field))['%s__min' % field]

    def values_field(self, owner, year, field):
        return [(query['date'].month, round(query[field], 3))
                for query in self.get_by_owner_year(owner, year)
                .values('date', field)]


class Utilities(models.Model):
    price_help_text = _("Required. Only numbers greater than zero")

    objects = UtilitiesManager()
    owner = models.ForeignKey(
        UtilitiesUser,
        on_delete=models.CASCADE
    )

    date = models.DateField(
        _('Date'),
    )
    date_added = models.DateTimeField(
        auto_now_add=True,
        null=False)
    date_last_edit = models.DateTimeField(
        auto_now=True
        )

    underpayment = models.FloatField(
        _('Underpayment'),
        null=False,
        blank=False,
        help_text=price_help_text,
        validators=[validate_price],
    )
    amount_to_pay = models.FloatField(
        _('Amount to pay'),
        null=False,
        blank=False,
        help_text=price_help_text,
        validators=[validate_price],
    )
    payments_last_mouth = models.FloatField(
        _('Payments last mouth'),
        null=False,
        blank=False,
        help_text=price_help_text,
        validators=[validate_price],
    )
    to_pay = models.FloatField(
        _('To pay'),
        null=False,
        blank=False,
        help_text=price_help_text,
        validators=[validate_price],
    )
    housing_stock = models.FloatField(
        _('Housing Stock'),
        null=False,
        blank=False,
        help_text=price_help_text,
        validators=[validate_price],
    )
    hws_thermal_energy_cp = models.FloatField(
        _('HWS: Thermal energy CP'),
        null=False,
        blank=False,
        help_text=price_help_text,
        validators=[validate_price],
    )
    hws_cold_water_cp = models.FloatField(
        _('HWS: Cold Water CP'),
        null=False,
        blank=False,
        help_text=price_help_text,
        validators=[validate_price],
    )
    cold_water_cp = models.FloatField(
        _('Cold Water CP'),
        null=False,
        blank=False,
        help_text=price_help_text,
        validators=[validate_price],
    )
    sewage_cp = models.FloatField(
        _('Sewage CP'),
        null=False,
        blank=False,
        help_text=price_help_text,
        validators=[validate_price],
    )
    electricity_cp = models.FloatField(
        _('Electricity CP'),
        null=False,
        blank=False,
        help_text=price_help_text,
        validators=[validate_price],
    )
    special_account_for_overhaul = models.FloatField(
        _('Special account for overhaul'),
        null=False,
        blank=False,
        help_text=price_help_text,
        validators=[validate_price],
    )
    home_heating = models.FloatField(
        _('Home Heating'),
        null=False,
        blank=False,
        help_text=price_help_text,
        validators=[validate_price],
    )
    hws_thermal_energy = models.FloatField(
        _('HWS: Thermal Energy'),
        null=False,
        blank=False,
        help_text=price_help_text,
        validators=[validate_price],
    )
    hws_cold_water = models.FloatField(
        _('HWS: Cold Water'),
        null=False,
        blank=False,
        help_text=price_help_text,
        validators=[validate_price],
    )
    cold_water = models.FloatField(
        _('Cold Water'),
        null=False,
        blank=False,
        help_text=price_help_text,
        validators=[validate_price],
    )
    sewage = models.FloatField(
        _('Sewage'),
        null=False,
        blank=False,
        help_text=price_help_text,
        validators=[validate_price],
    )
    garbage_service = models.FloatField(
        _('Garbage service'),
        null=False,
        blank=False,
        help_text=price_help_text,
        validators=[validate_price],
    )
    electricity = models.FloatField(
        _('Electricity'),
        null=False,
        blank=False,
        help_text=price_help_text,
        validators=[validate_price],
    )
    intercom_maintenance = models.FloatField(
        _('Intercom Maintenance'),
        null=False,
        blank=False,
        help_text=price_help_text,
        validators=[validate_price],
    )
    gate_maintenance = models.FloatField(
        _('Gate Maintenance'),
        null=False,
        blank=False,
        help_text=price_help_text,
        validators=[validate_price],
    )
    cctv_maintenance = models.FloatField(
        _('CCTV Maintenance'),
        null=False,
        blank=False,
        help_text=price_help_text,
        validators=[validate_price],
    )

    hws_cold_water_consumption = models.FloatField(
        _('HWS: Cold Water Consumption'),
        null=False,
        blank=False,
        help_text=price_help_text,
        validators=[validate_price],
    )
    cold_water_consumption = models.FloatField(
        _('Cold Water Consumption'),
        null=False,
        blank=False,
        help_text=price_help_text,
        validators=[validate_price],
    )
    sewage_consumption = models.FloatField(
        _('Sewage Consumption'),
        null=False,
        blank=False,
        help_text=price_help_text,
        validators=[validate_price],
    )
    electricity_consumption = models.FloatField(
        _('Electricity Consumption'),
        null=False,
        blank=False,
        help_text=price_help_text,
        validators=[validate_price],
    )

    def __str__(self):
        df = DateFormat(self.date)
        return df.format(get_format('DATE_FORMAT'))

utilities/forms.py
from django import forms
from django.forms import ModelForm

from .models import Utilities
from .utils import is_data_validation_error, is_date_validation_error

form_fields = [
    'date',
    'underpayment',
    'amount_to_pay',
    'payments_last_mouth',
    'housing_stock',
    'hws_thermal_energy_cp',
    'hws_cold_water_cp',
    'cold_water_cp',
    'sewage_cp',
    'electricity_cp',
    'special_account_for_overhaul',
    'home_heating',
    'hws_thermal_energy',
    'hws_cold_water',
    'cold_water',
    'sewage',
    'garbage_service',
    'electricity',
    'intercom_maintenance',
    'gate_maintenance',
    'cctv_maintenance',
    'hws_cold_water_consumption',
    'cold_water_consumption',
    'sewage_consumption',
    'electricity_consumption',
]


class DateInput(forms.DateInput):
    input_type = 'date'


class UtilitiesForm(ModelForm):

    class Meta:
        model = Utilities
        fields = form_fields
        # format fixed issue wrong date_format issue
        widgets = {
            'date': DateInput(format='%Y-%m-%d'),
        }

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        self.pk = kwargs.pop('pk', None)
        super(UtilitiesForm, self).__init__(*args, **kwargs)

    def clean_date(self):
        date = self.cleaned_data['date']
        if self.pk:
            edit_utilities = Utilities.objects.get(pk=self.pk)
            if date.month == edit_utilities.date.month:
                return date
        error = is_date_validation_error(self.user, date)
        if error:
            msg = u'This entry(%s) already exists!' % (error)
            raise forms.ValidationError(msg)

        return date

    def clean(self):
        cleaned_data = super().clean()
        error = is_data_validation_error(cleaned_data)
        if error:
            raise forms.ValidationError(error)

utilities/views.py
import json

from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.utils.safestring import mark_safe
from django.template.defaulttags import register
from django.views.generic import (
    TemplateView,
    CreateView,
    DetailView,
    ListView,
    UpdateView,
    DeleteView,
)
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin

from .forms import UtilitiesForm
from .models import Utilities

from celery import group
from core.tasks import get_field_data

# Custom tag for dict
@register.filter
def get_item(dictionary, key):
    return dictionary.get(key)

# Custom tag to format field
@register.filter
def format_field(field):
    return _(field.replace('_', ' ').capitalize().replace('Hws', 'HWS'))


@register.filter(is_safe=True)
def js(obj):
    return mark_safe(json.dumps(obj))


def get_stat_data(owner, fields):
    years_query_set = Utilities.objects.filter(owner=owner).distinct(
            'date__year'
            ).values_list(
                'date__year', flat=True)
    years = [year for year in years_query_set][::-1]

    stat_data = {field: {} for field in fields}
    job = group([
        get_field_data.s(owner.pk, field, years)
        for field in fields
    ])
    result = job.apply_async()
    data = result.join()
    for pair in data:
        stat_data[pair[0]] = pair[1]
    return stat_data


def is_stat_data_empty(stat_data):
    return all(value == {} for value in stat_data.values())


class HomeView(LoginRequiredMixin, TemplateView):
    template_name = 'home.html'

    def get_context_data(self, **kwargs):
        ctx = super(TemplateView, self).get_context_data(**kwargs)
        user = self.request.user
        stat_data = get_stat_data(
            user,
            [
                'amount_to_pay',
                'hws_cold_water_consumption',
                'cold_water_consumption',
                'sewage_consumption',
                'electricity_consumption',
            ]
        )
        ctx['stat_data'] = stat_data
        ctx['is_stat_data_empty'] = is_stat_data_empty(stat_data)
        return ctx


class CreateUtilitiesView(LoginRequiredMixin, CreateView):
    form_class = UtilitiesForm
    success_url = reverse_lazy('utilities:list')
    template_name = 'utilities_create.html'

    def get_form_kwargs(self):
        kwargs = super(CreateUtilitiesView, self).get_form_kwargs()
        kwargs.update({'user': self.request.user})
        return kwargs

    def form_valid(self, form):
        owner = self.request.user
        form.instance.owner = owner

        underpayment = form.instance.underpayment
        amount_to_pay = form.instance.amount_to_pay
        payments_last_mouth = form.instance.payments_last_mouth

        form.instance.to_pay = amount_to_pay - (
            payments_last_mouth - underpayment)
        return super(CreateUtilitiesView, self).form_valid(form)


class DetailUtilitiesView(LoginRequiredMixin, UserPassesTestMixin, DetailView):
    model = Utilities
    template_name = 'utilities_detail.html'
    context_object_name = 'utilities'

    def test_func(self):
        return self.get_object().owner == self.request.user


class ListUtilitiesView(LoginRequiredMixin, ListView):
    model = Utilities
    template_name = 'utilities_list.html'
    context_object_name = 'utilities_list'
    paginate_by = 6

    def get_queryset(self):
        return Utilities.objects.filter(
            owner=self.request.user
        ).order_by(
            '-date'
        )


class EditUtilitiesView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Utilities
    form_class = UtilitiesForm
    success_url = reverse_lazy('utilities:list')
    template_name = 'utilities_edit.html'

    def get_form_kwargs(self):
        kwargs = super(EditUtilitiesView, self).get_form_kwargs()
        kwargs.update({'user': self.request.user})
        kwargs.update({'pk': self.get_object().pk})
        return kwargs

    def form_valid(self, form):
        underpayment = form.instance.underpayment
        amount_to_pay = form.instance.amount_to_pay
        payments_last_mouth = form.instance.payments_last_mouth

        form.instance.to_pay = amount_to_pay - (
            payments_last_mouth - underpayment)
        return super(EditUtilitiesView, self).form_valid(form)

    def test_func(self):
        return self.get_object().owner == self.request.user


class DeleteUtilitiesView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Utilities
    success_url = reverse_lazy('utilities:list')

    def test_func(self):
        return self.get_object().owner == self.request.user

templates/utilities/utilities_create.html
{% extends 'base.html' %}

{% load i18n %}

{% load crispy_forms_tags %}

{% block title %}{% trans 'Add Utilities Entry'%}{% endblock %}

{% block content %}
<div class="container-fluid">
    <h2 class="form-header">{% trans 'Add Utilities Entry'%}</h2>
    <form method="post">
      {% csrf_token %}
      {{ form|crispy }}
      <button  class="btn btn-outline-success btn-block" type="submit">{% trans 'Save'%}</button>
    </form>
</div>
{% endblock content %}

templates/utilities/utilities_detail.html
{% extends 'base.html' %}

{% load i18n %}

{% block content %}
<div class="jumbotron jumbotron-fluid bg-info text-white text-center">
    <div class="container">
        <h1>{% trans 'Utilites Check for'%} {{ utilities }}</h1>      
        <p>{% trans 'Underpayment'%}: {{ utilities.underpayment }}</p>
        <p>{% trans 'Amount to pay'%}: {{ utilities.amount_to_pay }}</p>
        <p>{% trans 'Payments last mouth'%}: {{ utilities.payments_last_mouth }}</p>
        <h4>{% trans 'To pay'%}: {{ utilities.to_pay }}</h4>
        <div class="btn-group">
            <a href="{% url 'utilities:edit' utilities.pk %}" class="btn btn-success" role="button">{% trans 'Edit'%}</a>
            <a href='#' class="btn btn-danger" role="button">{% trans 'Delete'%}</a>
        </div>
    </div>
</div>
<div class="container-fluid">
    <div class="table-responsive">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>{% trans 'Servises'%}</th>
                    <th>{% trans 'Price'%}</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>{% trans 'Housing Stock'%}</td>
                    <td>{{ utilities.housing_stock }}</td>
                </tr>
                <tr>
                    <td>{% trans 'HWS: Thermal energy CP'%}</td>
                    <td>{{ utilities.hws_thermal_energy_cp }}</td>
                </tr>
                <tr>
                    <td>{% trans 'HWS: Cold Water CP'%}</td>
                    <td>{{ utilities.hws_cold_water_cp }}</td>
                </tr>
                <tr>
                    <td>{% trans 'Cold Water CP'%}</td>
                    <td>{{ utilities.cold_water_cp }}</td>
                </tr>
                <tr>
                    <td>{% trans 'Sewage CP'%}</td>
                    <td>{{ utilities.sewage_cp }}</td>
                </tr>
                <tr>
                    <td>{% trans 'Electricity CP'%}</td>
                    <td>{{ utilities.electricity_cp }}</td>
                </tr>
                <tr>
                    <td>{% trans 'Special account for overhaul'%}</td>
                    <td>{{ utilities.special_account_for_overhaul }}</td>
                </tr>
                <tr>
                    <td>{% trans 'Home Heating'%}</td>
                    <td>{{ utilities.home_heating }}</td>
                </tr>
                <tr>
                    <td>{% trans 'HWS: Thermal Energy'%}</td>
                    <td>{{ utilities.hws_thermal_energy }}</td>
                </tr>
                <tr>
                    <td>{% trans 'HWS: Cold Water'%}</td>
                    <td>{{ utilities.hws_cold_water }}</td>
                </tr>
                <tr>
                    <td>{% trans 'Cold Water'%}</td>
                    <td>{{ utilities.cold_water }}</td>
                </tr>
                <tr>
                    <td>{% trans 'Sewage'%}</td>
                    <td>{{ utilities.sewage }}</td>
                </tr>
                <tr>
                    <td>{% trans 'Garbage service'%}</td>
                    <td>{{ utilities.garbage_service }}</td>
                </tr>
                <tr>
                    <td>{% trans 'Electricity'%}</td>
                    <td>{{ utilities.electricity }}</td>
                </tr>
                <tr>
                    <td>{% trans 'Intercom Maintenance'%}</td>
                    <td>{{ utilities.intercom_maintenance }}</td>
                </tr>
                <tr>
                    <td>{% trans 'Gate Maintenance'%}</td>
                    <td>{{ utilities.gate_maintenance }}</td>
                </tr>
                <tr>
                    <td>{% trans 'CCTV Maintenance'%}</td>
                    <td>{{ utilities.cctv_maintenance }}</td>
                </tr>
            </tbody>
            <tfoot>
                <tr>
                    <td>{% trans 'Total'%}</td>
                    <td>{{ utilities.amount_to_pay }}</td>
                </tr>
            </tfoot>
        </table>
    </div>    
    <div class="table-responsive">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>{% trans 'Servises'%}</th>
                    <th>{% trans 'Norm'%}</th>
                    <th>{% trans 'Consumption'%}</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>{% trans 'HWS: Cold Water'%}</td>
                    <td>{{ user.hws_cold_water_norm }}</td>
                    <td>{{ utilities.hws_cold_water_consumption }}</td>
                </tr>
                <tr>
                    <td>{% trans 'Cold Water'%}</td>
                    <td>{{ user.cold_water_norm }}</td>
                    <td>{{ utilities.cold_water_consumption }}</td>
                </tr>
                <tr>
                    <td>{% trans 'Sewage'%}</td>
                    <td>{{ user.sewage_norm }}</td>
                    <td>{{ utilities.sewage_consumption }}</td>
                </tr>
                <tr>
                    <td>{% trans 'Electricity'%}</td>
                    <td>{{ user.electricity_norm }}</td>
                    <td>{{ utilities.electricity_consumption }}</td>
                </tr>
            </tbody>
        </table>
    </div> 
</div>
{% endblock content %}

templates/utilities/utilities_edit.html
{% extends 'base.html' %}

{% load i18n %}

{% load crispy_forms_tags %}

{% block title %}{% trans 'Utilities:'%}  {{ utilities }} {% endblock %}

{% block content %}
<div class="container">
  <h4 class="form-header">
      {% trans 'Edit Utilities'%} {{ utilities }}
  </h4>
  <form method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <button  class="btn btn-outline-success btn-block" type="submit">{% trans 'Save'%}</button>
  </form>
</div>
{% endblock content %}

templates/utilities/utilities_list.html
{% extends 'base.html' %}

{% load i18n %}

{% block content %}
<style>
    .utilities-col {
        padding: 1em .5em;
    }
</style>
<div class="container-fluid">
    <div class="row">
        {% for utilities in utilities_list %}
        <div class="col-sm-4 utilities-col">
            <div class="card text-center border-info w-100">
                <h5 class="card-header bg-info text-white">{{ utilities }}</h3>
                <div class="card-body">
                    <p class="card-text">{% trans 'Underpayment'%}: {{ utilities.underpayment }}</p>
                    <p class="card-text">{% trans 'Amount to pay'%}: {{ utilities.amount_to_pay }}</p>
                    <p class="card-text">{% trans 'Payments last mouth'%}: {{ utilities.payments_last_mouth }}</p>
                    <h4 class="card-title">{% trans 'To pay'%}: {{ utilities.to_pay }}</h4>
                </div>
                <div class="card-footer btn-toolbar">
                    <a href="{% url 'utilities:detail' utilities.pk %}" class="btn btn-outline-primary btn-block" role="button">{% trans 'More Info'%}</a>
                    <a href="{% url 'utilities:edit' utilities.pk %}" class="btn btn-outline-success btn-block" role="button">{% trans 'Edit'%}</a>
                    <button type="button" class="btn btn-outline-danger btn-block" data-toggle="modal" data-utilities="{{ utilities }}" data-pk="{{ utilities.pk }}" data-target="#deleteModal">
                            {% trans 'Delete'%}
                    </button>
                </div> 
            </div>
        </div>
        {% endfor %}
    </div>


    {% if is_paginated %}
    <ul class="pagination justify-content-center">
        {% if page_obj.has_previous %}
        <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
        {% else %}
        <li class="page-item disabled"><span class="page-link">&laquo;</span></li>
        {% endif %}
        {% for i in paginator.page_range %}
        {% if page_obj.number == i %}
        <li class="page-item active"><span class="page-link">{{ i }} <span class="sr-only">(current)</span></span></li>
        {% else %}
        <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
        {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
        <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
        {% else %}
        <li class="page-item disabled"><span class="page-link">&raquo;</span></li>
        {% endif %}
    </ul>
    {% endif %}

    <!-- The Delete Modal -->
    <div class="modal fade" id="deleteModal">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
            
                <div class="modal-header">
                    <h4 class="modal-title">{% trans 'Delete Entry'%}</h4>
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>
                
                <div class="modal-body">
                    Are you sure you want to delete Entry for 
                </div>
                
                <div class="modal-footer">
                    <form id="delete-form" method="POST">
                        {% csrf_token %}
                        <input class="btn btn-danger" type="submit" value="{% trans 'Delete'%}">
                        <button type="button" class="btn btn-light" data-dismiss="modal">{% trans 'Close'%}</button>
                    </form>
                </div>
                
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $('#deleteModal').on('show.bs.modal', function(e) {
        //Get data-id attribute of the clicked element
        var utilities = $(e.relatedTarget).data('utilities');
        var pk = $(e.relatedTarget).data('pk');
        //Make delete url
        url = "{% url 'utilities:delete' pk=12345 %}".replace(/12345/, pk.toString());
        //Populate the body
        $('.modal-body').html(`{% trans 'Are you sure you want to delete Entry for'%} <strong>${utilities}<strong>?`);
        //Set action
        $('#delete-form').attr('action', url);;
    });
</script>
{% endblock content %}