users/urls.py
from django.urls import path

from .views import SignUpView, DetailUserView, EditUserView

app_name = "users"
urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
    path('<str:username>/', DetailUserView.as_view(), name='detail'),
    path('<str:username>/edit/', EditUserView.as_view(), name='edit'),
]

utilities/urls.py
from django.urls import path

from .views import (
    CreateUtilitiesView,
    EditUtilitiesView,
    DeleteUtilitiesView,
    DetailUtilitiesView,
    ListUtilitiesView
)

app_name = "utilities"
urlpatterns = [
    path('', ListUtilitiesView.as_view(), name='list'),
    path('create/', CreateUtilitiesView.as_view(), name='create'),
    path('<int:pk>/', DetailUtilitiesView.as_view(), name='detail'),
    path('<int:pk>/edit/', EditUtilitiesView.as_view(), name='edit'),
    path('<int:pk>/delete/', DeleteUtilitiesView.as_view(), name='delete'),
]

utilities_stats/urls.py
from django.contrib import admin
from django.conf.urls.i18n import i18n_patterns
from django.urls import path, include
from django.views.generic import TemplateView
from django.views.defaults import (
    page_not_found,
    server_error,
    permission_denied
)

from rest_framework import routers

from api.views import UserViewSet, UtilitiesViewSet
from utilities.views import HomeView

from django.conf import settings

router = routers.DefaultRouter()
router.register(r'users', UserViewSet)
router.register(r'utilities', UtilitiesViewSet)

urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path('users/', include('django.contrib.auth.urls')),
    path('users/', include('users.urls')),
    path('utilities/', include('utilities.urls')),
    path('', HomeView.as_view(), name='home'),
    path(
        'about/',
        TemplateView.as_view(template_name='about.html'),
        name='about'
    ),
)

urlpatterns += [
    path('api/', include(router.urls)),
    path(
        'api/auth/',
        include('rest_framework.urls', namespace='rest_framework'),
    ),
]


def custom_page_not_found(request):
    return page_not_found(request, None)


def custom_permission_denied(request):
    return permission_denied(request, None)


if settings.DEBUG:
    urlpatterns += i18n_patterns(
        path("404/", custom_page_not_found),
        path("403/", custom_permission_denied),
        path("500/", server_error),
    )

templates/about.html
{% extends 'base.html' %}

{% load i18n %}

{% block title %}{% trans 'About' %}{% endblock %}

{% block content %}

<div class="container">
    <div class="card text-info border-info" style="margin: .5em 1em;">
        <div class="card-body">
            <h1 class="card-title">
                {% trans 'About' %} 
                <a class="text-info" href="https://github.com/TheSuperiorStanislav/practice-django-utilities_stats" target="_blank">
                    <i class="fa">&#xf113;</i>
                </a>
            </h1>
            <p>
                {% trans 'Umm, well, this is a small project built on Django for collecting and showing utilities checks stats data. Probably useless, made it just to practice Django.' %}
            </p>
        <div>
    </div>
    
</div>

{% endblock content %}

templates/base.html
{% load i18n %}

{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="theme-color" content="#222" />
    {% if user.dark_theme %}
        <link href="{% static 'css/bootstrap-dark.min.css' %}" rel="stylesheet">
    {% else %}
        <link href="{% static 'css/bootstrap-light.min.css' %}" rel="stylesheet">
    {% endif %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    
    <style>
        .form-header{
            margin: 1em .5em;
        }
        .form-help-text{
            margin: 1em .5em;
        }
        form {
            margin: 1em .5em;
        }
    </style>

    <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
    <script>
        (adsbygoogle = window.adsbygoogle || []).push({
            google_ad_client: "ca-pub-1486748127793857",
            enable_page_level_ads: true
        });
    </script>
    <title>
        {% block title %}Utilties Stats(DjangoProject){% endblock %}
    </title>
</head>
<body>
    <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
        <a class="navbar-brand" href="{% url 'home' %}">Utilties Stats-Django</a>
    
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
            <span class="navbar-toggler-icon"></span>
        </button>
        
        <div class="collapse navbar-collapse" id="collapsibleNavbar">
            <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'about' %}">{% trans 'About'%}</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'api-root' %}">API</a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item active dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
                            {% trans 'Hi'%} {{ user.username }}
                        </a>
                        <div class="dropdown-menu">
                            <a class="dropdown-item" href="{% url 'users:detail' user.username %}">
                                {% trans 'View account'%}
                            </a>
                            <a class="dropdown-item" href="{% url 'utilities:create' %}">
                                {% trans 'Add entry'%}
                            </a>
                            <a class="dropdown-item" href="{% url 'utilities:list' %}">
                                {% trans 'View all data'%}
                            </a>
                            <a class="dropdown-item" href="{% url 'logout' %}">
                                {% trans 'Log Out'%}
                            </a>
                        </div>
                    </li>
                {% else %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
                            {% trans 'Hi Guest'%}
                        </a>
                        <div class="dropdown-menu">
                            <a class="dropdown-item" href="{% url 'login' %}">{% trans 'Log In'%}</a>
                            <a class="dropdown-item" href="{% url 'users:signup' %}">{% trans 'Sign Up'%}</a>
                        </div>
                    </li>
                {% endif %}
                <li class="nav-item active">
                    <a href="" id="lang" class="nav-link"></a>
                </li>
            </ul>
        </div> 
    </nav>
    {% block content %}
    {% endblock content %}

    <script>
        $('document').ready(() => {
            var path = '{{ request.path }}'
            var cur_lang = path.split('/')[1]
            if (cur_lang == 'en'){
                path = path.replace(cur_lang,'ru')
                $("#lang").html('🇷🇺')
            }
            else {
                path = path.replace(cur_lang,'en')
                $("#lang").html('🇬🇧')
            }
            $("#lang").attr("href", path)
        })
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

templates/home.html
{% extends 'base.html' %}

{% load i18n %}

{% load static %}

{% block content %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.css" />
<div class="container-fluid" style="margin-top: 1em;" align="center">
    {% if not is_stat_data_empty %}
    {% for field, years in stat_data.items  %}
        <h3>{{ field|format_field }}</h3> 
        <ul class="nav nav-tabs">
            {% for year in years %}
            <li class="nav-item">
                <a class="nav-link" data-toggle="pill" href="#{{ field }}_{{ year }}">{{ year }}</a>
            </li>
            {% endfor %}
        </ul>
        <div class="tab-content" style="margin-bottom: 1em;">
            {% for year, data in years.items %}
                <div class="tab-pane container-fluid fade" id="{{ field }}_{{ year }}" style="padding: 1em .5em;">
                    <p>Avg: {{ data|get_item:'avg' }}</p>
                    <p>Sum: {{ data|get_item:'sum' }}</p>
                    <p>Max: {{ data|get_item:'max' }}</p>
                    <p>Min: {{ data|get_item:'min' }}</p>
                    <canvas id="{{ field }}_{{ year }}_visualization"></canvas>
                </div>
            {% endfor %}
        </div>
    {% endfor %}
    {% else %}
    <h2>{% trans 'No data to work with.' %}</h2>
    <a href="{% url 'utilities:create' %}" class="btn btn-outline-success" role="button">{% trans 'Add entry'%}</a>
    {% endif %}
</div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js"></script>
<script>
    var stat_data = JSON.parse('{{ stat_data|js }}')
</script>
<script src="{% static 'js/drawgraphs.js' %}"></script>
{% endblock content %}