users/urls.py
from django.urls import path

from .views import SignUpView, DetailUserView, EditUserView

app_name = "users"
urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
    path('<str:username>/', DetailUserView.as_view(), name='detail'),
    path('<str:username>/edit/', EditUserView.as_view(), name='edit'),
]

utilities_stats/urls.py
from django.contrib import admin
from django.conf.urls.i18n import i18n_patterns
from django.urls import path, include
from django.views.generic import TemplateView
from django.views.defaults import (
    page_not_found,
    server_error,
    permission_denied
)

from rest_framework import routers

from api.views import UserViewSet, UtilitiesViewSet
from utilities.views import HomeView

from django.conf import settings

router = routers.DefaultRouter()
router.register(r'users', UserViewSet)
router.register(r'utilities', UtilitiesViewSet)

urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path('users/', include('django.contrib.auth.urls')),
    path('users/', include('users.urls')),
    path('utilities/', include('utilities.urls')),
    path('', HomeView.as_view(), name='home'),
    path(
        'about/',
        TemplateView.as_view(template_name='about.html'),
        name='about'
    ),
)

urlpatterns += [
    path('api/', include(router.urls)),
    path(
        'api/auth/',
        include('rest_framework.urls', namespace='rest_framework'),
    ),
]


def custom_page_not_found(request):
    return page_not_found(request, None)


def custom_permission_denied(request):
    return permission_denied(request, None)


if settings.DEBUG:
    urlpatterns += i18n_patterns(
        path("404/", custom_page_not_found),
        path("403/", custom_permission_denied),
        path("500/", server_error),
    )

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils.translation import gettext_lazy as _

from core.validators import validate_norm


class UtilitiesUser(AbstractUser):
    price_help_text = _("Required. Only numbers greater than zero")

    email = models.EmailField(
        _('email address'),
        unique=True,)

    dark_theme = models.BooleanField(
         _('Dark theme'),
         default=False,
         null=False,
    )

    hws_cold_water_norm = models.FloatField(
        _('HWS Cold Water Norm'),
        null=True,
        blank=False,
        help_text=price_help_text,
        validators=[validate_norm],
    )
    cold_water_norm = models.FloatField(
        _('Cold Water Norm'),
        null=True,
        blank=False,
        help_text=price_help_text,
        validators=[validate_norm],
    )
    sewage_norm = models.FloatField(
        _('Sewage Norm'),
        null=True,
        blank=False,
        help_text=price_help_text,
        validators=[validate_norm],
    )
    electricity_norm = models.FloatField(
        _('Electricity Norm'),
        null=True,
        blank=False,
        help_text=price_help_text,
        validators=[validate_norm],
    )

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

from captcha.fields import ReCaptchaField

from .models import UtilitiesUser


class UtilitiesUserCreationForm(UserCreationForm):
    captcha = ReCaptchaField(label="I'm a human")

    def clean(self):
        cleaned_data = super().clean()
        if not cleaned_data.get('captcha'):
            raise forms.ValidationError("Complete Captcha!")

    class Meta(UserCreationForm.Meta):
        model = UtilitiesUser
        fields = [
            'email',
            'username',
        ]


class UtilitiesUserChangeForm(forms.ModelForm):

    class Meta:
        model = UtilitiesUser
        fields = [
            'first_name',
            'last_name',
            'dark_theme',
            'email',
            'hws_cold_water_norm',
            'cold_water_norm',
            'sewage_norm',
            'electricity_norm',
        ]

users/views.py
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, DetailView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin

from .forms import UtilitiesUserCreationForm, UtilitiesUserChangeForm
from .models import UtilitiesUser


class SignUpView(UserPassesTestMixin, CreateView):
    form_class = UtilitiesUserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'signup.html'

    def test_func(self):
        return not self.request.user.is_authenticated


class DetailUserView(LoginRequiredMixin, DetailView):
    model = UtilitiesUser
    template_name = 'user_detail.html'
    context_object_name = 'utilities_user'

    def get_context_data(self, **kwargs):
        ctx = super(DetailUserView, self).get_context_data(**kwargs)
        ctx['can_edit'] = self.get_object() == self.request.user
        return ctx

    def get_object(self):
        return UtilitiesUser.objects.get(username=self.kwargs.get("username"))


class EditUserView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = UtilitiesUser
    form_class = UtilitiesUserChangeForm
    template_name = 'user_edit.html'
    context_object_name = 'utilities_user'

    def get_success_url(self):
        return reverse("users:detail", kwargs={
            "username": self.kwargs.get("username")})

    def get_object(self):
        return UtilitiesUser.objects.get(username=self.kwargs.get("username"))

    def test_func(self):
        return self.get_object() == self.request.user

templates/users/edit_profile.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %}Edit Profile{% endblock title %}

{% block content %}
<div class="container">
    <h2>Edit Profile</h2>
    <form method="post">
      {% csrf_token %}
      {{ form|crispy }}
      <button  class="btn btn-success" type="submit">Save</button>
    </form>
</div>
{% endblock content %}

templates/users/signup.html
{% extends 'base.html' %}

{% load i18n %}

{% load crispy_forms_tags %}

{% block title %}{% trans 'Sign Up'%}{% endblock title %}

{% block content %}
<div class="container">
    <h2 class="form-header">{% trans 'Sign Up'%}</h2>
    <form method="post">
      {% csrf_token %}
      {{ form|crispy }}
      <button  class="btn btn-outline-success btn-block" type="submit">{% trans 'Sign Up'%}</button>
    </form>
</div>
{% endblock content %}

templates/users/user_detail.html
{% extends 'base.html' %}

{% load i18n %}

{% block title %}{% trans 'User' %}: {{ utilities_user.username }}{% endblock %}

{% block content %}
<div class="container-fluid">
    <div class="card text-white bg-primary" style="margin: 1em 0;">
        <div class="card-body">
            <h4 class="card-title">{% trans 'User' %}: {{ utilities_user.username }}</h4>
            <p class="card-text">{% trans 'Full name' %}: {{ utilities_user.first_name }} {{ utilities_user.last_name }}</p>
            <p class="card-text">E-mail: {{ utilities_user.email }}</p>
            <p class="card-text">{% trans 'Date joined' %}: {{ utilities_user.date_joined }}</p>
            <p class="card-text">{% trans 'Last login' %}: {{ utilities_user.last_login }}</p>
            {% if can_edit %}
            <div class="btn-group">
                <a href="{% url 'users:edit' utilities_user.username %}" class="btn btn-success">
                    {% trans 'Edit Info' %}
                </a>
                <a href="{% url 'password_change' %}" class="btn btn-success">
                    {% trans 'Change password' %}
                </a>
            </div>
            {% endif %}
        </div>
    </div>
    <div class="table-responsive" style="margin: 1em 0;">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>{% trans 'Servises' %}</th>
                    <th>{% trans 'Norm' %}</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>{% trans 'HWS: Cold Water' %}</td>
                    <td>{{ utilities_user.hws_cold_water_norm }}</td>
                </tr>
                <tr>
                    <td>{% trans 'Cold Water' %}</td>
                    <td>{{ utilities_user.cold_water_norm }}</td>
                </tr>
                <tr>
                    <td>{% trans 'Sewage' %}</td>
                    <td>{{ utilities_user.sewage_norm }}</td>
                </tr>
                <tr>
                    <td>{% trans 'Electricity' %}</td>
                    <td>{{ utilities_user.electricity_norm }}</td>
                </tr>
            </tbody>
        </table>
    </div> 
</div>
{% endblock content %}

templates/users/user_edit.html
{% extends 'base.html' %}

{% load i18n %}

{% load crispy_forms_tags %}

{% block title %}{% trans 'User'%}: {{ utilities_user.username }}{% endblock %}

{% block content %}
<div class="container">
  <h4 class="form-header">{% trans 'Edit Profile'%}</h4>
  <form method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <button  class="btn btn-outline-success btn-block" type="submit">{% trans 'Save'%}</button>
  </form>
</div>
{% endblock content %}